name: Blackbox Deploy

on:
  pull_request:
    tags:
      - v*.*.*

  workflow_dispatch:
      inputs:
        env:
          description: 'Environment to deploy'
          required: true
          default: 'dev'
        url:
          description: 'S3 URL to deploy to'
          required: true
          default: 's3://dev.testbot.win'
        version:
          description: 'Version to deploy'
          required: true
          default: 'latest'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.env }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload to S3
        run: |
          aws s3 sync ./dist/apps/testbot-app/browser ${{ github.event.inputs.url }}