name: ✅ Main Deployment Workflow

on:
  push:
    branches:
      - main
    # tags:
    #   - 'v*.*.*'

permissions:
  actions: read
  contents: read

jobs:
  dev:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci --legacy-peer-deps
      - uses: nrwl/nx-set-shas@v4
      - run: npx nx build testbot-app --configuration=production --skip-nx-cache
      # disabled for now so we always deploy
      #- run: npx nx affected -t lint test build --configuration=development --skip-nx-cache
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Upload to S3 Dev
        run: |
          aws s3 sync ./dist/apps/testbot-app/browser s3://dev.testbot.win
  prod:
    environment: prod
    runs-on: ubuntu-latest
    needs: dev
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci --legacy-peer-deps
      - uses: nrwl/nx-set-shas@v4
      - run: npx nx build testbot-app --configuration=production --skip-nx-cache
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Upload to S3 Prod
        run: |
          aws s3 sync ./dist/apps/testbot-app/browser s3://testbot.win
  libs:
    # only does the release notes lib for now
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci --legacy-peer-deps
      # - name: Check if GitHub Action was affected
      #   id: affected
      #   run: |
      #     npx nx show projects --affected --base=origin/main --head=HEAD > affected.txt
      #     cat affected.txt
      #     echo "affected=$(grep github-actions-generate-release-notes affected.txt)" >> $GITHUB_OUTPUT

      # - name: Build release notes lib
      #   if: steps.affected.outputs.affected != ''

      # building every time for now
      - name: Build release notes lib
        run: npx nx run generate-release-notes:build

      - name: List generated action files
        run: ls -R .github/actions/generate-release-notes

      - name: Run local action
        uses: ./.github/actions/generate-release-notes
