name: 🥈 Post Deploy Rev2

on:
  deployment_status:

permissions:
  actions: read
  contents: read
  issues: write

jobs:
  dev:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run local action
        uses: ./.github/actions/generate-release-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
