name: 🥈 Post Deploy Rev2

on:
  deployment_status:

permissions:
  actions: read
  contents: write
  issues: write

jobs:
  dev:
    environment: dev
    runs-on: ubuntu-latest
    if: >
      github.event.deployment.environment == 'dev' || 
      github.event.deployment.environment == 'prod' &&
      github.event.deployment_status.state == 'success'
    steps:
      - name: Set dynamic workflow name
        run: |
          if [ "${{ github.event.deployment.environment }}" = "prod" ]; then
            echo "Workflow run name=🚀 Publish Release" >> $GITHUB_ENV
          else
            echo "Workflow run name=🧪 Working on Draft Release..." >> $GITHUB_ENV
          fi
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run local action
        uses: ./.github/actions/generate-release-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
