name: 🥈 Post Deploy Rev2

on:
  deployment_status:

permissions:
  actions: read
  contents: read
  issues: write

jobs:
  dev:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run local action
        uses: ./.github/actions/generate-release-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
