name: 'hello?? My Test Workflow'

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  JSON: ${{ toJson(github.event) }}

jobs:
  # tester:
  #   uses: kghafari/my-actions/.github/workflows/action-three.yml@main
  #   with:
  #     test-value: 'my test value'
  script-tester:
    uses: kghafari/my-actions/.github/workflows/action-one-workflow.yml@main
    with:
      name: 'from testbot!'
