name:  My Test Workflow
run-name: Test Workflow for ${{ github.event.deployment.environment }} - ${{ github.event.deployment_status.state }}

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  JSON: ${{ toJson(github.event) }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test action
        uses: kghafari/my-actions/src/action-three@main
        with:
          test-value: 'my test value'
        # uses: kghafari/my-actions/src/playwright@main
        # with:
        #   base_url: google.com
        #   env: dev
        #   workflow_run_url: '${{ github.repository }}/actions/runs/${{ github.run_id }}'
