name: Test Workflow
run-name: Test Workflow for ${{ github.event.deployment.environment }} - ${{ github.event.deployment_status.state }}

on:
  deployment_status:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  JSON: ${{ toJson(github.event) }}

jobs:
  test:
    runs-on: ubuntu-latest
    if: >
      github.event.deployment_status.state == 'success'
    steps:
      - name: Set outputs
        id: vars
        run: echo "short_sha=${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - run: |
          echo "Triggered from: [${{ steps.vars.outputs.short_sha }}](${{ github.event.workflow_run.html_url }})" >> $GITHUB_STEP_SUMMARY

      - name: Other Jobs
        run: |
          echo "Begin 'other jobs'" >> $GITHUB_STEP_SUMMARY
          echo "GITHUB_SHA: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "GITHUB_REPOSITORY: ${{ github.repository }}" >> $GITHUB_STEP_SUMMARY
          echo "GITHUB_REF: ${{ github.ref }}" >> $GITHUB_STEP_SUMMARY
