name: Test Workflow

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    env:
      GITHUB_ENV: ${{ github.env }}
      GITHUB_PATH: ${{ github.path }}
      GITHUB_OUTPUT: ${{ github.output }}
      GITHUB_ACTION_PATH: ${{ github.action_path }}
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: ./.github/actions/hello
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number "$RANDOM_NUMBER"
        shell: bash
        env:
          RANDOM_NUMBER: ${{ steps.foo.outputs.random-number }}
      - run: echo "${{ github.workflow.env }} /n ${{ github.ref }}"
      - run: echo "${{ github.action.env }}"
      - run: echo "${{ github.job.env }}"
      - run: echo "${{ github.workflow.shas }}"