name:  'hello?? My Test Workflow'

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  JSON: ${{ toJson(github.event) }}

jobs:
  tester:
    uses: kghafari/my-actions/.github/workflows/action-three/action.yml@main
    with:
      test-value: 'my test value'
        # uses: kghafari/my-actions/src/playwright@main
        # with:
        #   base_url: google.com
        #   env: dev
        #   workflow_run_url: '${{ github.repository }}/actions/runs/${{ github.run_id }}'
