name: Test Workflow
run-name: Test Workflow for ${{ github.event.deployment.environment }} - ${{ github.event.deployment_status.state }}

on:
  deployment_status:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  JSON: ${{ toJson(github.event) }}

jobs:
  test:
    runs-on: ubuntu-latest
    if: >
      github.event.deployment_status.state == 'success'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: |
          echo "$JSON"
          echo "==========================="
          echo "Deployment Status Environment URL:"
          echo "Environment URL: ${{ github.event.deployment_status.environment_url }}"
          echo "Triggered from: [${{ github.event.workflow_run.html_url }}](${{ github.event.workflow_run.html_url }})" >> $GITHUB_STEP_SUMMARY
