name: Test Workflow
run-name: Test Workflow for ${{ github.event.deployment.environment }} - ${{ github.event.deployment_status.state }}

on:
  deployment_status:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  JSON: ${{ toJson(github.event) }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test action
        uses: kghafari/my-actions/src/playwright@v1
        with:
          workflow-run: '${{ github.event.workflow_run }}'
    #   - run: |
    #       echo "$JSON"
    #   - run: |
    #       echo "Triggered from: [${{ github.event.workflow_run.name }} - #${{github.event.workflow_run.run_number}} / ${{ github.event.workflow_run.id }} ](${{ github.event.workflow_run.html_url }})" >> $GITHUB_STEP_SUMMARY
