name:  My Test Workflow
run-name: Test Workflow for ${{ github.event.deployment.environment }} - ${{ github.event.deployment_status.state }}

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  JSON: ${{ toJson(github.event) }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: test action
        uses: kghafari/my-actions/src/playwright@main
        with:
          base_url: google.com
          environment: dev
          workflow_run_url: '${{ github.repository }}/actions/runs/${{ github.run_id }}'
